spring:
    application:
        name: defiant-server
    profiles:
        active: dev
    config:
        import: configserver:http://localhost:8888
    cloud:
        config:
            username: admin
            password: admin
